// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ePieHut.Entities.Entities;

public partial class Order
{
    public string Id { get; set; }

    public string PaymentId { get; set; }

    public string Street { get; set; }

    public string ZipCode { get; set; }

    public string City { get; set; }

    public string Locality { get; set; }

    public string PhoneNumber { get; set; }

    public DateTime CreatedDate { get; set; }

    public int UserId { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual User User { get; set; }
}